name: Task
description: Create a task that follows lab workflow/expectations/handbook.
body:
- type: textarea
  attributes:
    label: Task Description/List & Learning Resources/Helping Teammates
    description: What info is needed to ensure a good understanding of the task/problem? Resources or team member help needed to finish the task.
- type: input
  attributes:
    label: Deliverable, Test, Reviewer
- type: checkboxes
  attributes:
    label: Before Working on This Task (Updated 7/19)
    options:
      - label: "I agree the following:\n1. I will provide update/plan next (after each work session) & keep lab calendar updated and come.\n2. I will follow the [lab workflow](https://github.com/TheRARELab/handbook/blob/main/Workflow/) (e.g., start/end date, open/update tasks on project board) & [expectations](https://github.com/TheRARELab/handbook/blob/main/Expectations.md) in [handbook](https://github.com/TheRARELab/handbook/).\n3. I will reply to my teammate promptly (please also do outside of work session; only a few minutes)."
